receptor = /home/ubuntu/xylanase-thesis/docking/proteins/1O8S_A_Repair.pdbqt
center_x = 5.629
center_y = 50.005
center_z = 8.017
size_x = 22.0
size_y = 22.0
size_z = 22.0
exhaustiveness = 12
num_modes = 9
