receptor = /home/ubuntu/xylanase-thesis/docking/proteins/1T6G_A_Repair.pdbqt
center_x = 43.293
center_y = 11.676
center_z = 0.338
size_x = 22.0
size_y = 22.0
size_z = 22.0
exhaustiveness = 12
num_modes = 9
