receptor = /home/ubuntu/xylanase-thesis/docking/proteins/2C79_A_Repair.pdbqt
center_x = 2.541
center_y = 25.316
center_z = 0.161
size_x = 22.0
size_y = 22.0
size_z = 22.0
exhaustiveness = 12
num_modes = 9
