receptor = /home/ubuntu/xylanase-thesis/docking/proteins/3NIY_A_Repair.pdbqt
center_x = -16.064
center_y = -12.346
center_z = -13.393
size_x = 28.0
size_y = 28.0
size_z = 28.0
exhaustiveness = 12
num_modes = 9
