receptor = /home/ubuntu/xylanase-thesis/docking/proteins/6KVV_A_Repair.pdbqt
center_x = -13.489
center_y = -21.956
center_z = -12.347
size_x = 22.0
size_y = 22.0
size_z = 22.0
exhaustiveness = 12
num_modes = 9
