receptor = /home/ubuntu/xylanase-thesis/docking/proteins/7K4P_A_Repair.pdbqt
center_x = 8.935
center_y = 27.265
center_z = 40.542
size_x = 28.0
size_y = 28.0
size_z = 28.0
exhaustiveness = 12
num_modes = 9
