receptor = /home/ubuntu/xylanase-thesis/docking/proteins/7K4X_A_Repair.pdbqt
center_x = 17.851
center_y = 1.947
center_z = 28.997
size_x = 28.0
size_y = 28.0
size_z = 28.0
exhaustiveness = 12
num_modes = 9
