receptor = /home/ubuntu/xylanase-thesis/docking/proteins/8QY3_A_Repair.pdbqt
center_x = 2.715
center_y = 21.249
center_z = -9.788
size_x = 22.0
size_y = 22.0
size_z = 22.0
exhaustiveness = 12
num_modes = 9
